id: A21032191
title: Toh_298-The_Gandi_Sutra-v2
type: translation
pechas:
- I49D557BB
- I972428C4
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-071-012
  eft-text-version: 1.1.3 2020
  title: Toh_298-The_Gandi_Sutra-v2
alignment_to_base:
  I49D557BB/8DC1: 2B11
  I972428C4/F991: 2B11
